### ISSUE TITLE
Upscale (i.e., increase the pixel size) of a satellite image using a Gaussian filter (point spread function)

### ISSUE THREAD

**Issue by nikosGeography** [cran/OpenImageR#1]
I want to resample a raster from 15m to 460m (factor ~30.6) using a Gaussian filter.
**The goal**

I have a coarse resolution image which I want to downscale (i.e., increase the spatial resolution). I also have a fine resolution band to assist the downscaling. The downscaling method I am using is called geographically weighted area-to-point regression Kriging (GWATPRK). The method consists of two steps:

1. GWR and,
2. ATPK on the GWR's residuals.

In order to perform GWR using raster data, those needs to have the same pixel size. This means that, my fine resolution image needs to be upscaled to match the spatial resolution of the coarse band. This upscaling of the fine band needs to be done using a Gaussian kernel (i.e., the PSF) with sigma (std) = 0.5. I have found that the `down_sample_image` function might do what I want to achieve, that is upscale the fine resolution band using a PSF (in my case, the PSF is assumed to be Gaussian).

In the function I mentioned, I used both the `gaussian_blur = T` and `gaussian_blur = F`. The results were different (obviously). So my questions are:

1. Should I use _TRUE_ or _FALSE_ for the `gaussian_blur`?
2. What's their difference?

For reference, I am leaving the link to the [paper](https://www.sciencedirect.com/science/article/pii/S092427162030229X) I am following (p. 253, Eq(9)).

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by nikosGeography** [comment]
I am sorry I didn't know that. I will delete post in 5 minutes. Many thanks.

**Comment by gaborcsardi** [comment]
No worries, no need to delete.
